Always set REMOTE_USER when valid auth provided (even if not required).
deshaw/wsgi-kerberos pull request #18
Opened 2019-12-29 20:10 UTC by twosigmajab

Interpret "auth not required" (i.e. `auth_required_callback` returning False)
to mean: missing/invalid auth will not result in a 40x error,
but if a client provides valid auth, it will now be exposed to the app.

This better supports cases where auth is not required for a particular request
(e.g. a health check endpoint hit anonymously by Kubernetes),
but it is still useful to know who made the request when valid auth is provided
(e.g. a script or user interactively hitting the health check endpoint
from a client that does pre-emptive Kerberos).

Includes unit tests and also updates the "Changes" section of the README.

2019-12-29 20:11 UTC, twosigmajab commented
I based this off my branch with the fix for #16, since I wanted to incorporate that fix in this revision. If this PR is accepted, GitHub should automatically resolve #17 and #16 along with it.

2020-01-06 18:22 UTC, twosigmajab commented
Thanks for reviewing, @hawicz!

2020-12-15 22:03 UTC, propertone requested changes

2020-12-15 22:03 UTC, propertone commented on wsgi_kerberos.py
> +            )
Can you rewrite this as a regular if/else block? It's more readable and whitespace isn't expensive.

2020-12-15 22:03 UTC, propertone commented on wsgi_kerberos.py
> +            return _40x_resp_if_auth_required(self._unauthorized)
I think this is incorrect - if auth is not required, but the client sends an authorization header that doesn't include a user (ie: to verify mutual authentication), then it should send back a 401 with a server token in any case (@mkomitee correct me if I'm wrong).

2020-12-15 22:15 UTC, twosigmajab commented on wsgi_kerberos.py
> +            return _40x_resp_if_auth_required(self._unauthorized)
This gave me pause too, but based on https://tools.ietf.org/html/rfc4559#page-4 I think it's correct? (Note the 403 behavior in this `elif` block is not introduced by this PR, it is pre-existing.)

> If a 401 containing a "WWW-Authenticate" header with "Negotiate" and gssapi-data is returned from the server, it is a continuation of the authentication request.

Based on the RFC and the code's interpretation, I believe 401 means "please try (or continue trying) to authenticate", whereas 403 is overloaded and means either "you authenticated but are not authorized", or, "you tried to authenticate, it failed, and you should not continue trying". Responding with another 401 in that latter case would indicate you want the client to keep trying, which you don't.

2020-12-15 22:16 UTC, twosigmajab commented on wsgi_kerberos.py
> +            return _40x_resp_if_auth_required(self._unauthorized)
So 403 rather than 401 is preferable for the "Negotiate INVALID" case to stop the client from continuing GSSAPI negotiation. Does that make sense?

2020-12-17 01:22 UTC, propertone commented on wsgi_kerberos.py
> +            return _40x_resp_if_auth_required(self._unauthorized)
The issue here is the `server_token` variable is no longer passed to `self._unauthorized` if auth is required. Multi-round trip negotiate cycle is technically a normal part of the GSS-API security context establishment spec (though not much used in practice). From https://www.researchgate.net/figure/SIP-REGISTER-message-flow-with-GSS-API-security-context-establishment-authentication_fig4_230585165 :

```
...Depending on the underlying security mechanism, additional token exchanges may be required in the course of context establishment. If so, GSS_S_CONTINUE_NEEDED status is set and additional tokens are passed between the client and server until a security context is established,...
```

2020-12-17 13:19 UTC, twosigmajab commented on wsgi_kerberos.py
> +            return _40x_resp_if_auth_required(self._unauthorized)
Sorry I initially misunderstood what you were saying. Thanks for the good catch; should be fixed in the latest revision. Another look?

2020-12-17 13:19 UTC, twosigmajab commented on wsgi_kerberos.py
> +            )
Done in the latest revision.

2020-12-17 22:58 UTC, propertone approved these changes
Looks good

2020-12-17 23:00 UTC, merged